### ISSUE TITLE
Container not honoring arguments

### ISSUE THREAD

**Issue by stephanrenggli** [dr1s/sonarr_exporter.py#1]
Hi, I just tried to use this exporter in a docker container and it seems the arguments passed to the script are not being used, aka. the default values are used.

I tried to run this with docker-compose, therefore I am passing the required arguments with the command: function as described in the read me.

Can you reproduce this behavior or am I doing something wrong?

**Comment by dr1s** [comment]
Hi, 

thanks for the report and sorry for the late reply.

I have the same problem with the image pulled from docker hub.
Funnily rebuilding the image seems to work, after installing the dependencies again (the lock file seems to be outdated).
Let me know if the image i just uploaded works for you

**Comment by stephanrenggli** [comment]
Thanks for the reply, I just tested the new image but it didn't seem to fix the issue.
This is what gets passed through docker cmd: `--sonarr http://sonarr:8989 --interface 0.0.0.0 --port 9314 --api-key <key>`

And this is the error log, still referring to "localhost" instead of "sonarr".

![image](https://user-images.githubusercontent.com/5135902/51038882-8b7c8180-15b4-11e9-9df4-9948c9b17eff.png)

**Comment by dr1s** [comment]
You could try and build the image by yourself.
I sadly have not enough time to debug this issue currently.

> cd sonarr_exporter.py
> docker build -t dr1s/sonarr_exporter .

**Comment by stephanrenggli** [comment]
Thanks, I will try this when I have some time and let you know.

**Comment by stephanrenggli** [comment]
I have gotten around to testing this again, so I was doing something wrong the first time.

This is my docker-compose setup for reference:
```
sonarr_exporter:
    container_name: sonarr_exporter
    image: dr1s/sonarr_exporter:latest
    restart: always
    command: --sonarr http://sonarr:8989 --interface 0.0.0.0 --port 9314 --api-key <key>
    networks:
      - <network>
```
